name: Auto Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  auto-release:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # nécessaire pour récupérer les tags existants

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run auto release script (SemVer + Conventional Commits)
        id: release_step
        run: |
          python scripts/release.py --auto || echo "No release performed"

      - name: Push commit and tags (if any)
        if: success()
        run: |
          # Vérifier s'il y a un commit local non poussé
          if [ -n "$(git log origin/main..HEAD --oneline)" ]; then
            git push origin main --follow-tags || git push origin main && git push --tags || true
          else
            echo "Aucun nouveau commit à pousser (pas de release)."
          fi

